<a href="https://colab.research.google.com/github/Techbasu/master_solidity/blob/master/AbaloneAgePrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Here we would be predicting the age of the abalone fish

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Dependant and Independant Values and convert SEX from categorical to binary

In [2]:
df= pd.read_csv('Abalone.csv')
binary={'SEX':{'M':1,'F':0,'I':2}}
df=df.replace(binary)
df

SEX  Measure  Diameter  Height  Weight  Meat_Weight  Gut_Weight  \
0       1    0.455     0.365   0.095  0.5140       0.2245      0.1010   
1       1    0.350     0.265   0.090  0.2255       0.0995      0.0485   
2       0    0.530     0.420   0.135  0.6770       0.2565      0.1415   
3       1    0.440     0.365   0.125  0.5160       0.2155      0.1140   
4       2    0.330     0.255   0.080  0.2050       0.0895      0.0395   
...   ...      ...       ...     ...     ...          ...         ...   
4172    0    0.565     0.450   0.165  0.8870       0.3700      0.2390   
4173    1    0.590     0.440   0.135  0.9660       0.4390      0.2145   
4174    1    0.600     0.475   0.205  1.1760       0.5255      0.2875   
4175    0    0.625     0.485   0.150  1.0945       0.5310      0.2610   
4176    1    0.710     0.555   0.195  1.9485       0.9455      0.3765   

      Shell_Weight  Rings  
0           0.1500     15  
1           0.0700      7  
2           0.2100      9  
3           0.1550     10  
4           0.0550      7  
...            ...    ...  
4172        0.2490     11  
4173        0.2605     10  
4174        0.3080      9  
4175        0.2960     10  
4176        0.4950     12  

[4177 rows x 9 columns]

In [3]:
X=df.iloc[:,1:].values
Y=df.iloc[:, 0].values

In [4]:
print(X)

[[ 0.455   0.365   0.095  ...  0.101   0.15   15.    ]
 [ 0.35    0.265   0.09   ...  0.0485  0.07    7.    ]
 [ 0.53    0.42    0.135  ...  0.1415  0.21    9.    ]
 ...
 [ 0.6     0.475   0.205  ...  0.2875  0.308   9.    ]
 [ 0.625   0.485   0.15   ...  0.261   0.296  10.    ]
 [ 0.71    0.555   0.195  ...  0.3765  0.495  12.    ]]


In [5]:
print(Y)

[1 1 0 ... 1 0 1]


## Splitting the datasets into train and test sets

In [6]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test= tts(X,Y,test_size=0.20,random_state=0)

In [7]:
print(x_train)

[[1.800e-01 1.350e-01 8.000e-02 ... 7.000e-03 1.000e-02 5.000e+00]
 [2.150e-01 1.500e-01 5.500e-02 ... 9.000e-03 1.250e-02 3.000e+00]
 [6.600e-01 5.300e-01 1.700e-01 ... 2.120e-01 4.530e-01 1.500e+01]
 ...
 [5.950e-01 4.500e-01 1.450e-01 ... 2.065e-01 2.535e-01 1.000e+01]
 [6.250e-01 4.900e-01 1.650e-01 ... 2.365e-01 3.185e-01 9.000e+00]
 [4.100e-01 3.250e-01 1.100e-01 ... 7.500e-02 1.010e-01 8.000e+00]]


In [8]:
print(x_test)

[[5.500e-01 4.250e-01 1.550e-01 ... 2.430e-01 3.350e-01 1.300e+01]
 [5.000e-01 4.000e-01 1.200e-01 ... 1.430e-01 1.935e-01 8.000e+00]
 [6.200e-01 4.800e-01 1.550e-01 ... 3.740e-01 3.175e-01 1.100e+01]
 ...
 [4.450e-01 3.450e-01 1.050e-01 ... 1.015e-01 1.170e-01 7.000e+00]
 [5.400e-01 4.350e-01 1.800e-01 ... 2.260e-01 3.250e-01 1.700e+01]
 [2.500e-01 1.750e-01 6.000e-02 ... 8.000e-03 2.000e-02 4.000e+00]]


In [9]:
print(y_train)

[2 2 1 ... 1 0 2]


In [10]:
print(y_test)

[1 2 1 2 1 0 1 1 2 1 2 2 0 1 2 0 1 1 0 2 2 2 2 0 2 1 1 1 2 1 1 2 0 0 2 1 2
 1 2 0 1 0 1 1 0 1 1 0 2 2 0 2 0 0 1 1 1 1 2 2 1 1 1 2 2 1 1 1 2 0 2 1 0 0
 0 2 1 0 1 1 0 2 2 0 2 2 1 1 2 2 2 0 1 2 1 2 2 1 1 0 0 2 0 1 2 0 2 2 2 1 1
 1 0 0 1 1 1 0 2 2 2 0 2 2 1 0 0 0 2 0 0 0 1 1 0 1 1 2 2 1 0 1 2 1 0 1 2 2
 2 2 2 1 2 0 1 2 2 2 1 1 1 1 2 0 2 2 2 2 1 2 2 1 0 1 1 1 2 2 1 1 2 0 1 2 2
 1 1 2 2 1 0 0 2 1 1 0 2 1 2 0 0 1 1 1 0 0 1 0 2 0 2 2 0 1 1 2 2 1 2 1 1 1
 2 0 1 1 1 1 1 2 1 1 2 0 1 1 2 2 2 1 0 0 0 0 2 2 0 2 1 1 1 1 1 1 2 0 2 2 2
 0 0 1 0 1 2 2 0 2 2 1 0 1 1 1 2 0 0 1 0 0 2 0 2 1 0 1 2 0 1 0 2 2 2 2 2 1
 2 2 2 0 0 1 0 2 0 2 1 0 0 0 0 1 2 2 0 0 2 2 2 1 0 1 1 1 0 0 2 2 0 1 2 1 2
 2 2 1 1 1 1 1 2 1 0 0 1 2 2 1 1 2 2 2 1 1 1 1 0 0 2 0 1 1 2 1 2 0 2 1 1 1
 0 2 0 2 0 1 0 2 0 2 1 1 1 0 1 1 0 1 2 2 1 0 1 1 0 2 1 2 1 1 2 0 2 0 0 1 1
 0 1 0 1 2 1 2 0 2 2 1 0 0 0 2 0 1 2 2 1 0 0 0 2 1 0 1 2 0 0 0 1 0 2 2 0 2
 2 2 0 2 1 0 1 2 1 2 2 1 1 1 0 0 2 1 1 0 1 1 1 0 1 1 1 1 2 1 2 1 2 2 1 1 0
 0 1 1 0 1 0 0 2 0 2 0 1 

## Using Feature Scaling for putting all the values in the same scale in training and testing sets

In [11]:
from sklearn.preprocessing import StandardScaler as SSC
sc= SSC()
x_train= sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [12]:
print(x_train)

[[-2.88863777 -2.77572159 -1.41092732 ... -1.58940432 -1.65503169
  -1.54702766]
 [-2.59633945 -2.62402222 -1.99755535 ... -1.57129213 -1.6371499
  -2.17103097]
 [ 1.12002486  1.21902846  0.70093358 ...  0.26709517  1.51362157
   1.57298889]
 ...
 [ 0.57718513  0.40996516  0.11430555 ...  0.21728665  0.0866547
   0.01298061]
 [ 0.82772654  0.81449681  0.58360797 ...  0.4889695   0.55158125
  -0.29902104]
 [-0.96782026 -0.85419625 -0.70697369 ... -0.97358986 -1.00413452
  -0.6110227 ]]


In [13]:
print(x_test)

[[ 0.20137301  0.15713288  0.34895676 ...  0.54783412  0.66960106
   0.94898558]
 [-0.21619602 -0.0956994  -0.47232248 ... -0.35777539 -0.34250827
  -0.6110227 ]
 [ 0.78596964  0.7133639   0.34895676 ...  1.73418258  0.54442853
   0.32498227]
 ...
 [-0.67552194 -0.65193042 -0.82429929 ... -0.73360334 -0.88969106
  -0.92302435]
 [ 0.1178592   0.25826579  0.93558479 ...  0.3938805   0.5980739
   2.1969922 ]
 [-2.30404114 -2.37118994 -1.88022974 ... -1.58034823 -1.58350453
  -1.85902932]]


## Here we will be using Decision Tree Regression for better prediction results

In [14]:
from sklearn.tree import DecisionTreeRegressor as DTR
clf= DTR(random_state=42).fit(x_train,y_train)

## Predicting age on the actual dataset

In [15]:
predvalue= clf.predict(sc.transform([[0.356,0.23,0.080,0.620,0.1144,0.0200,0.45,5]]))
print("age is: ",predvalue)

age is:  [1.]


## predicting on the test set

In [16]:
y_pred= clf.predict(x_test)

In [19]:
y_pred

array([0., 0., 1., 2., 1., 0., 1., 1., 0., 0., 1., 2., 0., 0., 2., 2., 2.,
       0., 1., 2., 2., 2., 0., 1., 2., 1., 2., 1., 2., 0., 2., 2., 1., 1.,
       2., 2., 2., 0., 2., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1.,
       2., 2., 0., 0., 2., 2., 1., 2., 2., 1., 0., 0., 2., 2., 1., 0., 1.,
       2., 1., 2., 1., 1., 0., 1., 0., 2., 2., 0., 2., 0., 2., 0., 0., 1.,
       2., 0., 1., 1., 2., 1., 1., 2., 2., 2., 2., 2., 2., 1., 0., 1., 2.,
       1., 0., 2., 1., 2., 2., 2., 0., 1., 1., 0., 1., 0., 0., 0., 0., 2.,
       0., 2., 0., 2., 2., 1., 2., 1., 0., 1., 1., 1., 2., 1., 1., 0., 1.,
       2., 2., 2., 0., 1., 0., 2., 1., 0., 2., 1., 2., 1., 2., 1., 1., 2.,
       0., 1., 2., 0., 1., 1., 2., 1., 2., 1., 0., 2., 1., 2., 2., 2., 2.,
       2., 2., 2., 2., 1., 1., 2., 2., 1., 1., 2., 0., 1., 2., 1., 0., 1.,
       2., 2., 0., 0., 2., 2., 0., 1., 2., 0., 2., 1., 0., 0., 1., 1., 0.,
       1., 0., 2., 0., 0., 1., 2., 2., 2., 0., 0., 2., 2., 0., 2., 1., 1.,
       1., 1., 1., 0., 0.

## Comparing the real value with predicted value

In [17]:
data= pd.DataFrame({"Real Values" : y_test, "Predicted Values" : y_pred})
print(data)

     Real Values  Predicted Values
0              1               0.0
1              2               0.0
2              1               1.0
3              2               2.0
4              1               1.0
..           ...               ...
831            0               1.0
832            1               0.0
833            2               2.0
834            1               0.0
835            2               1.0

[836 rows x 2 columns]


## Evaluating the model

In [18]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

-0.16008859712326218