<a href="https://colab.research.google.com/github/Techbasu/master_solidity/blob/master/BANK_DECISIONTREE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## IMPORTING LIBRARIES

In [1]:
import numpy as np
import pandas as pd

## IMPORTING DATASET AND CHECKING INFO

In [2]:
df= pd.read_csv('BANK.csv')

In [3]:
df

id  age     sex      region    income married  children  car  \
0    ID12101   48  FEMALE  INNER_CITY  17546.00      NO         1   NO   
1    ID12102   40    MALE        TOWN  30085.10     YES         3  YES   
2    ID12103   51  FEMALE  INNER_CITY  16575.40     YES         0  YES   
3    ID12104   23  FEMALE        TOWN  20375.40     YES         3   NO   
4    ID12105   57  FEMALE       RURAL  50576.30     YES         0   NO   
..       ...  ...     ...         ...       ...     ...       ...  ...   
595  ID12696   61  FEMALE  INNER_CITY  47025.00      NO         2  YES   
596  ID12697   30  FEMALE  INNER_CITY   9672.25     YES         0  YES   
597  ID12698   31  FEMALE        TOWN  15976.30     YES         0  YES   
598  ID12699   29    MALE  INNER_CITY  14711.80     YES         0   NO   
599  ID12700   38    MALE        TOWN  26671.60      NO         0  YES   

    save_act current_act mortgage  pep  
0         NO          NO       NO  YES  
1         NO         YES      YES   NO  
2        YES         YES       NO   NO  
3         NO         YES       NO   NO  
4        YES          NO       NO   NO  
..       ...         ...      ...  ...  
595      YES         YES      YES   NO  
596      YES         YES       NO   NO  
597      YES          NO       NO  YES  
598      YES          NO      YES   NO  
599       NO         YES      YES  YES  

[600 rows x 12 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   id           600 non-null    object 
 1   age          600 non-null    int64  
 2   sex          600 non-null    object 
 3   region       600 non-null    object 
 4   income       600 non-null    float64
 5   married      600 non-null    object 
 6   children     600 non-null    int64  
 7   car          600 non-null    object 
 8   save_act     600 non-null    object 
 9   current_act  600 non-null    object 
 10  mortgage     600 non-null    object 
 11  pep          600 non-null    object 
dtypes: float64(1), int64(2), object(9)
memory usage: 56.4+ KB


## CLEANING THE DATA

In [5]:
df['sex'].value_counts()

FEMALE    300
MALE      300
Name: sex, dtype: int64

In [6]:
convert= {'sex': {'FEMALE':0, 'MALE':1},'married':{'NO':0, 'YES':1},
          'region':{'INNER_CITY':1,'TOWN':2,'RURAL':3,'SUBURBAN':4},
          'car':{'NO':0, 'YES':1},'save_act':{'NO':0, 'YES':1},
          'current_act':{'NO':0, 'YES':1},'mortgage':{'NO':0, 'YES':1}}

In [7]:
df= df.replace(convert)
df

id  age  sex  region    income  married  children  car  save_act  \
0    ID12101   48    0       1  17546.00        0         1    0         0   
1    ID12102   40    1       2  30085.10        1         3    1         0   
2    ID12103   51    0       1  16575.40        1         0    1         1   
3    ID12104   23    0       2  20375.40        1         3    0         0   
4    ID12105   57    0       3  50576.30        1         0    0         1   
..       ...  ...  ...     ...       ...      ...       ...  ...       ...   
595  ID12696   61    0       1  47025.00        0         2    1         1   
596  ID12697   30    0       1   9672.25        1         0    1         1   
597  ID12698   31    0       2  15976.30        1         0    1         1   
598  ID12699   29    1       1  14711.80        1         0    0         1   
599  ID12700   38    1       2  26671.60        0         0    1         0   

     current_act  mortgage  pep  
0              0         0  YES  
1              1         1   NO  
2              1         0   NO  
3              1         0   NO  
4              0         0   NO  
..           ...       ...  ...  
595            1         1   NO  
596            1         0   NO  
597            0         0  YES  
598            0         1   NO  
599            1         1  YES  

[600 rows x 12 columns]

## TAKING DEPENDANT AND INDEPENDANT VALUES

In [8]:
X= df.iloc[:, 1:-1].values
Y= df.iloc[:, -1].values

In [9]:
print(X)

[[48.  0.  1. ...  0.  0.  0.]
 [40.  1.  2. ...  0.  1.  1.]
 [51.  0.  1. ...  1.  1.  0.]
 ...
 [31.  0.  2. ...  1.  0.  0.]
 [29.  1.  1. ...  1.  0.  1.]
 [38.  1.  2. ...  0.  1.  1.]]


In [10]:
print(Y)

['YES' 'NO' 'NO' 'NO' 'NO' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES'
 'YES' 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO'
 'YES' 'NO' 'YES' 'NO' 'NO' 'YES' 'NO' 'YES' 'NO' 'NO' 'YES' 'NO' 'NO'
 'YES' 'NO' 'YES' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES' 'NO' 'NO' 'NO' 'YES'
 'YES' 'NO' 'YES' 'YES' 'YES' 'NO' 'YES' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO'
 'NO' 'NO' 'NO' 'YES' 'NO' 'YES' 'YES' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO'
 'YES' 'YES' 'NO' 'NO' 'YES' 'YES' 'YES' 'NO' 'NO' 'NO' 'YES' 'YES' 'NO'
 'YES' 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'NO' 'YES' 'NO' 'YES' 'NO' 'YES'
 'NO' 'NO' 'NO' 'YES' 'NO' 'YES' 'NO' 'NO' 'YES' 'YES' 'NO' 'NO' 'NO'
 'YES' 'YES' 'NO' 'YES' 'YES' 'YES' 'YES' 'YES' 'NO' 'NO' 'NO' 'YES' 'NO'
 'NO' 'NO' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'YES' 'NO' 'NO' 'NO' 'NO'
 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES' 'NO' 'YES' 'NO'
 'NO' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO'
 'NO' 'NO' 'YES' 'YES' 'YES' 'NO' 'YES' 'YES' 'YES' 'YES' 'YES

## SPLITTING THE DEPENDANT AND INDEPENDANT
## VARIABLES

In [11]:
xc=['age','sex','region','income','married','children','car','save_act','current_act','mortgage']
yc=['YES','NO']

In [12]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test= tts(X,Y,test_size=0.25,random_state=0)

In [13]:
print(x_train)

[[50.  0.  1. ...  1.  1.  0.]
 [60.  0.  1. ...  1.  1.  1.]
 [18.  1.  4. ...  1.  1.  0.]
 ...
 [52.  0.  1. ...  1.  0.  0.]
 [64.  0.  3. ...  1.  1.  0.]
 [67.  0.  4. ...  0.  1.  1.]]


In [14]:
print(x_test)

[[47.  1.  1. ...  1.  0.  0.]
 [36.  0.  2. ...  1.  0.  1.]
 [57.  1.  3. ...  1.  1.  0.]
 ...
 [30.  1.  1. ...  0.  1.  0.]
 [41.  0.  4. ...  0.  0.  0.]
 [24.  1.  3. ...  1.  1.  0.]]


In [15]:
print(y_train)

['YES' 'NO' 'NO' 'YES' 'NO' 'YES' 'YES' 'YES' 'YES' 'YES' 'YES' 'YES' 'NO'
 'YES' 'YES' 'NO' 'NO' 'YES' 'YES' 'NO' 'YES' 'YES' 'NO' 'YES' 'YES' 'NO'
 'YES' 'NO' 'YES' 'YES' 'YES' 'NO' 'YES' 'NO' 'YES' 'YES' 'YES' 'NO' 'NO'
 'NO' 'NO' 'NO' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'NO' 'YES' 'NO' 'NO' 'NO'
 'NO' 'YES' 'NO' 'YES' 'NO' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'NO' 'NO'
 'NO' 'NO' 'NO' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES'
 'YES' 'NO' 'YES' 'YES' 'NO' 'NO' 'YES' 'YES' 'NO' 'YES' 'YES' 'YES' 'NO'
 'YES' 'YES' 'YES' 'NO' 'NO' 'YES' 'NO' 'YES' 'YES' 'YES' 'NO' 'NO' 'NO'
 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES' 'NO'
 'YES' 'NO' 'YES' 'NO' 'YES' 'YES' 'NO' 'NO' 'YES' 'NO' 'NO' 'NO' 'NO'
 'YES' 'NO' 'YES' 'YES' 'YES' 'NO' 'YES' 'NO' 'NO' 'YES' 'NO' 'YES' 'NO'
 'YES' 'NO' 'YES' 'YES' 'NO' 'NO' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO'
 'NO' 'NO' 'YES' 'YES' 'YES' 'YES' 'NO' 'NO' 'NO' 'YES' 'NO' 'NO' 'NO'
 'NO' 'NO' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES'

In [16]:
print(y_test)

['NO' 'YES' 'YES' 'YES' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES' 'YES'
 'NO' 'YES' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES' 'NO' 'NO' 'YES' 'NO' 'YES'
 'NO' 'YES' 'NO' 'NO' 'NO' 'YES' 'YES' 'NO' 'NO' 'YES' 'YES' 'NO' 'YES'
 'NO' 'NO' 'YES' 'YES' 'YES' 'NO' 'YES' 'YES' 'NO' 'YES' 'YES' 'NO' 'NO'
 'NO' 'NO' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES' 'YES' 'NO' 'YES' 'NO' 'YES'
 'YES' 'NO' 'NO' 'YES' 'YES' 'NO' 'YES' 'YES' 'YES' 'NO' 'YES' 'YES' 'NO'
 'NO' 'NO' 'NO' 'NO' 'YES' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES' 'NO'
 'YES' 'YES' 'NO' 'YES' 'YES' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES' 'NO' 'YES'
 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'NO' 'YES' 'NO' 'NO' 'YES' 'NO' 'YES' 'NO'
 'NO' 'YES' 'NO' 'YES' 'YES' 'NO' 'NO' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO'
 'YES' 'NO' 'NO' 'NO' 'NO' 'YES' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'YES'
 'NO' 'YES' 'NO' 'YES' 'NO']


## APPLICATION OF DECISION TREE CLASSIFICATION

In [17]:
from sklearn.tree import DecisionTreeClassifier as DTC
clf= DTC(random_state=0).fit(x_train,y_train)

In [18]:
clf.score(x_test,y_test)

0.8266666666666667

## PLOTTING GRAPH OF DECISION TREE

In [19]:
from sklearn.tree import export_graphviz
from six import StringIO
from IPython.display import Image
import pydotplus
import graphviz

In [20]:
dot_data= StringIO()
export_graphviz(clf,out_file=dot_data,filled=True,special_characters=True,feature_names=xc,class_names=yc)
graph= pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_png('Tree.png')
Image(graph.create_png)
display(Image)

IPython.core.display.Image