<a href="https://colab.research.google.com/github/Techbasu/master_solidity/blob/master/Heart_Disease_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## In this project we are going to look for whether an person is prone to heart disease or not

## Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Reading the Dataset

In [2]:
df= pd.read_csv("Heart_Disease.csv")
X= df.iloc[:, :-1].values
Y= df.iloc[:, -1].values

In [3]:
print(X)

[[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]]


In [4]:
print(Y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0]


## Splitting the independant and dependant values into training and testing sets

In [5]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test= tts(X,Y,test_size=0.2,random_state=0)

## Feature Scaling on training and testing set of independent values

In [6]:
from sklearn.preprocessing import StandardScaler as SSC
sc= SSC()
x_train= sc.fit_transform(x_train)
x_test= sc.transform(x_test)

## Applying Dimensionality Reduction Algorithm [PCA]

In [7]:
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
x_train= pca.fit_transform(x_train)
x_test= pca.transform(x_test)

## Applying classification algorithm i.e
## [Logistic regression]

In [8]:
from sklearn.linear_model import LogisticRegression as LGR
lgr= LGR(random_state=0)
lgr.fit(x_train,y_train)

LogisticRegression(random_state=0)

## Predicted Test Result

In [16]:
y_pred= lgr.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 1]]


## Predicting whether a person is prone to heart disease or not

In [32]:
confirm_heart_disease=lgr.predict(pca.transform(sc.transform([[50,1,2,120,180,1,1,150,0,1,2,0,3]])))
print(confirm_heart_disease)

[1]


## Model score for estimation

In [15]:
lgr.score(x_train,y_train)

0.8181818181818182

## Confusion Matrix

In [18]:
from sklearn.metrics import confusion_matrix as CM, accuracy_score as AS
cm=CM(y_pred,y_test)
print(cm)

[[21  6]
 [ 6 28]]


In [19]:
AS(y_pred,y_test)

0.8032786885245902