<a href="https://colab.research.google.com/github/Techbasu/master_solidity/blob/master/hiring_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing important header files

In [38]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Reading csv file and allocation independent and dependent variables and working with the missing values and also conversion from categorical to numerical


In [39]:
df=pd.read_csv('hiring.csv')
## for categorical values
df= df.fillna(df.mode().iloc[0])
print(df) # LOCF[Last Observation Carry Forward]
from word2number import w2n
df.experience= df.experience.apply(w2n.word_to_num)
print('\n')
print(df)
X=df.iloc[:,:-1].values#independent
Y=df.iloc[:, -1].values#dependent

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0     eleven                    8.0                           9      50000
1     eleven                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    7.0                           7      72000
7     eleven                    7.0                           8      80000


   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0          11                    8.0                           9      50000
1          11                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2      

In [40]:
print(X)

[[11.  8.  9.]
 [11.  8.  6.]
 [ 5.  6.  7.]
 [ 2. 10. 10.]
 [ 7.  9.  6.]
 [ 3.  7. 10.]
 [10.  7.  7.]
 [11.  7.  8.]]


In [41]:
print(Y)

[50000 45000 60000 65000 70000 62000 72000 80000]


## Splitting into train and test data sets


In [42]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test= tts(X,Y,test_size=0.2,random_state=0)

In [43]:
print(x_train)

[[11.  8.  6.]
 [11.  7.  8.]
 [ 2. 10. 10.]
 [11.  8.  9.]
 [ 3.  7. 10.]
 [ 7.  9.  6.]]


In [44]:
print(x_test)

[[10.  7.  7.]
 [ 5.  6.  7.]]


In [45]:
print(y_train)

[45000 80000 65000 50000 62000 70000]


In [46]:
print(y_test)

[72000 60000]


##Applying multiple linear regression on training set

In [47]:
from sklearn.linear_model import LinearRegression as LR
lr= LR().fit(x_train,y_train)

## Prediction on Test set

In [48]:
y_pred= lr.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),(y_test.reshape(len(y_test),1))),1))

[[62935.67 72000.  ]
 [71441.86 60000.  ]]


Evaluation of Model Performance

In [49]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

-1.9594211269965038

## Looking through coefficient and intercept

In [51]:
print(lr.predict([[2,9,6]]))
print(lr.predict([[12,10,10]]))

[68599.48]
[50345.33]


In [53]:
print(lr.coef_)
print(lr.intercept_)

[-1208.31 -2464.64  -926.6 ]
98757.45242940274
