<a href="https://colab.research.google.com/github/Techbasu/master_solidity/blob/master/Housepricedetection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [57]:
df=pd.read_csv('homeprices.csv')
X=df.iloc[:,:-1].values
Y=df.iloc[:, -1].values

In [58]:
print(X)

[[2.6e+03 3.0e+00 2.0e+01]
 [3.0e+03 4.0e+00 1.5e+01]
 [3.2e+03     nan 1.8e+01]
 [3.6e+03 3.0e+00 3.0e+01]
 [4.0e+03 5.0e+00 8.0e+00]]


In [59]:
print(Y)

[550000 565000 610000 595000 760000]


## Working with missing data

In [60]:
from sklearn.impute import SimpleImputer
si= SimpleImputer(missing_values=np.nan, strategy='mean')
X=si.fit_transform(X)

In [61]:
print(X)

[[2.60e+03 3.00e+00 2.00e+01]
 [3.00e+03 4.00e+00 1.50e+01]
 [3.20e+03 3.75e+00 1.80e+01]
 [3.60e+03 3.00e+00 3.00e+01]
 [4.00e+03 5.00e+00 8.00e+00]]


## splitting the data into train and test data

In [62]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test = tts(X,Y,test_size=0.2,random_state=0)

In [63]:
print(x_train)

[[2.6e+03 3.0e+00 2.0e+01]
 [3.0e+03 4.0e+00 1.5e+01]
 [3.6e+03 3.0e+00 3.0e+01]
 [4.0e+03 5.0e+00 8.0e+00]]


In [64]:
print(x_test)

[[3200.      3.75   18.  ]]


In [65]:
print(y_train)

[550000 565000 595000 760000]


In [66]:
print(y_test)

[610000]


## Applying Multiple linear regression on training set

In [67]:
from sklearn.linear_model import LinearRegression as LR
lr=LR().fit(x_train,y_train)

## Prediction on the test set

In [68]:
y_pred=lr.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[598656.25 610000.  ]]


## Evaluation of Model performance

In [69]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:918: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)


nan

## predicting home prices with following inputs
## 3000 sqft 3 bedrooms age: 40
## 2500 sqrt 4 bedrooms age: 5

In [70]:
ans1=lr.predict([[3000,3,40]])
ans2=lr.predict([[2500,4,5]])
print(ans1)
print(ans2)

[262000.]
[638125.]


## Getting the final multiple linear regression equation

In [71]:
print(lr.coef_)
print(lr.intercept_)

[    236.25 -175125.    -19125.  ]
843625.0000000007


Putting in the formula:
price= b1*Area+b2*Bedroom+b3*Age+b

In [73]:
price = 236.25*3000+ -175125*3 + -19125*40 + 843625.0000000007
print(price)

262000.0000000007
