## Import numpy 

In [1]:
import numpy as np

## 1. Numpy arange() function

In [2]:
A=np.arange(1,20,2)# start=1,stop=20, step=2
print(A)

[ 1  3  5  7  9 11 13 15 17 19]


In [3]:
AA=np.arange(1,20,2, dtype=float)# start=1,stop=20, step=2
print(AA)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]


## 2. Creating Numpy array()

In [4]:
mylist=[[1,2,3],[2,3,4],[4,5,6]]
num_array=np.array(mylist)
print(num_array)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


In [5]:
arr= np.array([[1,2,4],[3,1,5],[9,8,5]])
print(arr)

[[1 2 4]
 [3 1 5]
 [9 8 5]]


## Creating array using empty()

In [6]:
nmp=np.empty([3,2])
print(nmp)
#return uninitialized array

[[4.65803448e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


## Creating array using eye()

In [7]:
nmp1=np.eye(3,3)
print(nmp1)
## creating an 2D array with 1 in diagonals and all other elements as zero

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Creating array as identity()

In [8]:
nmp2=np.identity(3)
print(nmp2)
## creating an Identity element

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Creating array as linspace()

In [9]:
ARR=np.linspace(0,20,11)# Creating floating point array
ARR_INT=np.linspace(0,20,11, dtype= int) # Creating integer array
print(ARR);print(ARR_INT)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]
[ 0  2  4  6  8 10 12 14 16 18 20]


## Creating array as logspace()

In [10]:
num_arr=np.logspace(0,4,5, dtype=int)
print(num_arr)
# returns an ndarray object that contains the numbers that are evenly spaced on a log scale

[    1    10   100  1000 10000]


## Creating array using zeros and ones

In [11]:
one_array=np.ones((2,3), dtype=int)
zero_array=np.zeros((2,3),dtype=int)
print(one_array);print(zero_array)
# creating numpy array of 1s and 0s

[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]


## The reshape function returns a new array by reshaping a new array

In [12]:
RA= np.arange(1,21,2)
Ra= RA.reshape(5,2)
print(RA);print(Ra)

[ 1  3  5  7  9 11 13 15 17 19]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]


## Creating array and fetching dtype,itemsize,ndim,shape,size

In [13]:
Raa=np.arange(1,41,2).reshape(5,4)
print(Raa);print(Raa.dtype);print(Raa.itemsize);print(Raa.ndim);print(Raa.shape);print(Raa.size)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]
 [33 35 37 39]]
int64
8
2
(5, 4)
20


## Accessing 1D ndarray object

In [16]:
B=np.arange(1,21,4)
print(B)
print(B[2])
print(B[0:4:1])## Accessing through slicing
print(B[-1:-3:-1])## Accessing through slicing
print(B>10)## Accessing using Boolean array indexing

[ 1  5  9 13 17]
9
[ 1  5  9 13]
[17 13]
[False False False  True  True]


## Accessing 2D ndarray object

In [27]:
C=np.arange(1,61,2).reshape(6,5)
print(C)
print(C[2][2])
print(C[1:10:2])
rowsum=C.sum(-1)
print(rowsum)
print(C[rowsum>48,:])

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]
 [51 53 55 57 59]]
25
[[11 13 15 17 19]
 [31 33 35 37 39]
 [51 53 55 57 59]]
[ 25  75 125 175 225 275]
[[11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]
 [51 53 55 57 59]]


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=eecf2c8b-05d0-4fc2-8af9-3d2d18e36ef4' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>