<a href="https://colab.research.google.com/github/Techbasu/master_solidity/blob/master/Penguin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## IMPORT THE LIBRARIES

In [62]:
import numpy as np
import pandas as pd

## READING THE DATASET AND CLEANING THE DATASET AS WELL

In [63]:
df=pd.read_csv('Penguins.csv')
con={'species':{'Adelie':0,'Gentoo':1,'Chinstrap':2},
     'island':{'Torgersen':0,'Biscoe':1,'Dream':2},
     'sex':{'male':0, 'female':1}
     }
df= df.replace(con)
def swap_columns(df, col1, col2):
    col_list = list(df.columns)
    x, y = col_list.index(col1), col_list.index(col2)
    col_list[y], col_list[x] = col_list[x], col_list[y]
    df = df[col_list]
    return df

df=swap_columns(df,'sex','year')
df['sex']=df['sex'].fillna(df['sex'].median())
X=df.iloc[:, 1:-1].values
Y=df.iloc[:,-1].values

In [64]:
print(X)

[[0.000e+00 0.000e+00 3.910e+01 ... 1.810e+02 3.750e+03 2.007e+03]
 [0.000e+00 0.000e+00 3.950e+01 ... 1.860e+02 3.800e+03 2.007e+03]
 [0.000e+00 0.000e+00 4.030e+01 ... 1.950e+02 3.250e+03 2.007e+03]
 ...
 [2.000e+00 2.000e+00 4.960e+01 ... 1.930e+02 3.775e+03 2.009e+03]
 [2.000e+00 2.000e+00 5.080e+01 ... 2.100e+02 4.100e+03 2.009e+03]
 [2.000e+00 2.000e+00 5.020e+01 ... 1.980e+02 3.775e+03 2.009e+03]]


In [65]:
print(Y)

[0. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0.
 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0.
 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.
 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0.
 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.
 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.
 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.
 1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0.
 1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.
 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.
 1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0.
 1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0.
 1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1.
 1. 0. 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 0. 1.

In [66]:
print(df)

     rowid  species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0        1        0       0            39.1           18.7              181.0   
1        2        0       0            39.5           17.4              186.0   
2        3        0       0            40.3           18.0              195.0   
3        4        0       0             NaN            NaN                NaN   
4        5        0       0            36.7           19.3              193.0   
..     ...      ...     ...             ...            ...                ...   
339    340        2       2            55.8           19.8              207.0   
340    341        2       2            43.5           18.1              202.0   
341    342        2       2            49.6           18.2              193.0   
342    343        2       2            50.8           19.0              210.0   
343    344        2       2            50.2           18.7              198.0   

     body_mass_g  year  sex

## TREATING MISSING VALUES IN INDEPENDANT VALUE

In [67]:
from sklearn.impute import SimpleImputer as SI
imp_mean= SI(missing_values=np.nan,strategy='mean')
X=imp_mean.fit_transform(X)

In [68]:
print(X)

[[0.000e+00 0.000e+00 3.910e+01 ... 1.810e+02 3.750e+03 2.007e+03]
 [0.000e+00 0.000e+00 3.950e+01 ... 1.860e+02 3.800e+03 2.007e+03]
 [0.000e+00 0.000e+00 4.030e+01 ... 1.950e+02 3.250e+03 2.007e+03]
 ...
 [2.000e+00 2.000e+00 4.960e+01 ... 1.930e+02 3.775e+03 2.009e+03]
 [2.000e+00 2.000e+00 5.080e+01 ... 2.100e+02 4.100e+03 2.009e+03]
 [2.000e+00 2.000e+00 5.020e+01 ... 1.980e+02 3.775e+03 2.009e+03]]


## ENCODING DEPENDANT VARIABLE

In [69]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y= le.fit_transform(Y)

In [70]:
print(Y)

[0 1 1 0 1 0 1 0 0 0 0 0 1 0 0 1 1 0 1 0 1 0 1 0 0 1 0 1 1 0 1 0 1 0 1 0 0
 1 1 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 0 1 0 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 0 1
 1 0 1 0 1 0 1 0 0 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 0 1 0 0 1 1
 0 1 0 1 0 1 0 1 0 1 0 0 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 0 0 1 0
 1 0 0 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 0 1 1 0 1 0 1 0 0 0 1
 0 1 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 1 0 0 1 0 1 1 0 1 0 1 0 1 0 1 0 0 1 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1 0 1 1 0 1 0 0 1 1 0 1 0 1 0 1
 0 0 1 0 1 1 0 1 0 0 1]


## SPLITTING INTO TRAIN AND TEST SETS

In [71]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test=tts(X,Y,test_size=0.20,random_state=0)

In [72]:
print(x_train)

[[0.000e+00 2.000e+00 4.230e+01 ... 1.910e+02 4.150e+03 2.007e+03]
 [2.000e+00 2.000e+00 4.970e+01 ... 1.950e+02 3.600e+03 2.008e+03]
 [2.000e+00 2.000e+00 4.980e+01 ... 1.980e+02 3.675e+03 2.009e+03]
 ...
 [0.000e+00 0.000e+00 3.730e+01 ... 1.990e+02 3.775e+03 2.009e+03]
 [0.000e+00 2.000e+00 3.750e+01 ... 1.790e+02 2.975e+03 2.007e+03]
 [1.000e+00 1.000e+00 5.020e+01 ... 2.180e+02 5.700e+03 2.007e+03]]


In [73]:
print(x_test)

[[0.000e+00 2.000e+00 4.060e+01 1.720e+01 1.870e+02 3.475e+03 2.009e+03]
 [0.000e+00 0.000e+00 3.890e+01 1.780e+01 1.810e+02 3.625e+03 2.007e+03]
 [0.000e+00 1.000e+00 3.570e+01 1.690e+01 1.850e+02 3.150e+03 2.008e+03]
 [1.000e+00 1.000e+00 4.690e+01 1.460e+01 2.220e+02 4.875e+03 2.009e+03]
 [0.000e+00 1.000e+00 3.450e+01 1.810e+01 1.870e+02 2.900e+03 2.008e+03]
 [2.000e+00 2.000e+00 4.760e+01 1.830e+01 1.950e+02 3.850e+03 2.008e+03]
 [0.000e+00 0.000e+00 3.880e+01 1.760e+01 1.910e+02 3.275e+03 2.009e+03]
 [1.000e+00 1.000e+00 5.430e+01 1.570e+01 2.310e+02 5.650e+03 2.008e+03]
 [1.000e+00 1.000e+00 4.850e+01 1.500e+01 2.190e+02 4.850e+03 2.009e+03]
 [0.000e+00 1.000e+00 3.500e+01 1.790e+01 1.920e+02 3.725e+03 2.009e+03]
 [0.000e+00 1.000e+00 4.100e+01 2.000e+01 2.030e+02 4.725e+03 2.009e+03]
 [1.000e+00 1.000e+00 4.750e+01 1.420e+01 2.090e+02 4.600e+03 2.008e+03]
 [0.000e+00 2.000e+00 3.210e+01 1.550e+01 1.880e+02 3.050e+03 2.009e+03]
 [2.000e+00 2.000e+00 4.520e+01 1.780e+01 1.980e+02

In [74]:
print(y_train)

[0 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 0 1 0 1 1 1 0 1 1 0 1 1 0 0 0 0
 1 1 0 1 1 1 0 0 0 1 1 0 0 0 1 0 1 0 1 1 0 1 0 1 0 0 0 1 0 1 0 1 0 1 1 0 0
 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1 0 1 0 1 0 1 0 1 0 0 0 0 1 1 0 1 0 1
 1 1 0 0 0 1 0 1 1 0 0 0 1 1 1 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 1 0
 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 1 1 1 1 0 0 0 1 0 1 1
 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 1 0 1 0 1 0 1 0 1 0 0 1 0 0 0 0 1 1 0
 0 1 1 0 1 1 1 1 1 0 0 1 1 0 1 0 0 1 1 1 1 0 1 0 0 1 0 0 0 1 1 0 0 1 0 0 0
 1 0 1 1 0 1 0 0 0 0 0 0 1 0 0 0]


In [75]:
print(y_test)

[0 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 0 0 1 0 1 1 1 0 0 0
 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 1 1 0 1 1 0 1 0 1 0 1 0 0 1 0 1 0]


## FEATURE SCALING

In [76]:
from sklearn.preprocessing import StandardScaler as SSC
sc= SSC()
x_train=sc.fit_transform(x_train)
x_test= sc.transform(x_test)

In [77]:
print(x_train)

[[-1.01555331  1.11701004 -0.34188472 ... -0.74257793 -0.09250803
  -1.20944862]
 [ 1.59451361  1.11701004  1.04668715 ... -0.45514497 -0.7816421
   0.        ]
 [ 1.59451361  1.11701004  1.06545163 ... -0.23957025 -0.68766927
   1.20944862]
 ...
 [-1.01555331 -1.75381015 -1.28010896 ... -0.16771201 -0.56237217
   1.20944862]
 [-1.01555331  1.11701004 -1.24257999 ... -1.6048768  -1.564749
  -1.20944862]
 [ 0.28948015 -0.31840006  1.14050957 ...  1.19759454  1.84959707
  -1.20944862]]


In [78]:
print(x_test)

[[-1.01555331e+00  1.11701004e+00 -6.60880962e-01  1.08411947e-03
  -1.03001088e+00 -9.38263479e-01  1.20944862e+00]
 [-1.01555331e+00 -1.75381015e+00 -9.79877202e-01  3.00383833e-01
  -1.46116032e+00 -7.50317824e-01 -1.20944862e+00]
 [-1.01555331e+00 -3.18400057e-01 -1.58034071e+00 -1.48565737e-01
  -1.17372736e+00 -1.34547907e+00  0.00000000e+00]
 [ 2.89480149e-01 -3.18400057e-01  5.21281575e-01 -1.29588131e+00
   1.48502749e+00  8.15895970e-01  1.20944862e+00]
 [-1.01555331e+00 -3.18400057e-01 -1.80551453e+00  4.50033690e-01
  -1.03001088e+00 -1.65872182e+00  0.00000000e+00]
 [ 1.59451361e+00  1.11701004e+00  6.52632969e-01  5.49800261e-01
  -4.55144969e-01 -4.68399341e-01  0.00000000e+00]
 [-1.01555331e+00 -1.75381015e+00 -9.98641687e-01  2.00617262e-01
  -7.42577927e-01 -1.18885769e+00  1.20944862e+00]
 [ 2.89480149e-01 -3.18400057e-01  1.90985345e+00 -7.47165165e-01
   2.13175165e+00  1.78694852e+00  0.00000000e+00]
 [ 2.89480149e-01 -3.18400057e-01  8.21513331e-01 -1.09634816e+0

## TRAINING THE LOGISTIC REGRESSION MODEL ON THE TRAINING SET

In [79]:
from sklearn.linear_model import LogisticRegression as LGR
lgr= LGR(random_state=0)
lgr.fit(x_train,y_train)

LogisticRegression(random_state=0)

## PREDICTING THE NEW RESULT[SEX OF PENGUIN]

In [80]:
lgr.predict(sc.transform([[2,0,37.8,21,187,4510,2008]]))

array([0])

In [81]:
lgr.predict(sc.transform([[0,2,25,17,178,3567,2008]]))

array([1])

## PREDICTING THE NEW TEST SET RESULT

In [82]:
y_pred= lgr.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]]


## APPLYING CONFUSION MATRIX FOR THE PREDICTED AND TEST RESULT

In [89]:
from sklearn.metrics import confusion_matrix as CM ,accuracy_score as asc
cm=CM(y_pred,y_test)
print("Confusion matrix:")
print(cm)
print("Accuracy score: ",asc(y_pred,y_test))

Confusion matrix:
[[28  4]
 [ 2 35]]
Accuracy score:  0.9130434782608695
